version: "3.3"
services:
  gatsby:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GIT_AUTHOR_EMAIL=uilton.dev@gmail.com
      - GIT_COMMITTER_EMAIL=uilton.dev@gmail.com
      - GIT_AUTHOR_NAME=Uilton Oliveira
      - GIT_COMMITTER_NAME=DarkSupremo
    volumes:
      - .:/site

  gatsby-develop:
    extends:
      service: gatsby
    command: gatsby develop --host 0.0.0.0

  gatsby-build:
    extends:
      service: gatsby
    command: gatsby build

  gatsby-serve:
    extends:
      service: gatsby
    command: gatsby serve --host 0.0.0.0
