version: "3.3"
services:
  gatsby-develop:
    ports:
      - "8000:8000"
    env_file:
      - git_settings.env
    volumes:
      - .:/site
    command: gatsby develop --host 0.0.0.0

  gatsby-build:
    ports:
      - "8000:8000"
    env_file:
      - git_settings.env
    volumes:
      - .:/site
    command: gatsby build

  gatsby-serve:
    ports:
      - "8000:8000"
    env_file:
      - git_settings.env
    volumes:
      - .:/site
    command: gatsby serve --host 0.0.0.0
